FILE DRIVER = 5A5CB8CA-9382-4E0C-B383-77FB517CD9EB {
    SECTION DXE_DEPEX = instantnoodlep/AdcDxe/AdcDxe.depex
    SECTION PE32 = instantnoodlep/AdcDxe/AdcDxe.efi
    SECTION UI = "AdcDxe"
  }

FILE DRIVER = B8D9777E-D72A-451F-9BDB-BAFB52A68415 {
    SECTION DXE_DEPEX = instantnoodlep/ArmCpuDxe/ArmCpuDxe.depex
    SECTION PE32 = instantnoodlep/ArmCpuDxe/ArmCpuDxe.efi
    SECTION UI = "ArmCpuDxe"
  }  
  
FILE DRIVER = DE371F7C-DEC4-4D21-ADF1-593ABCC15882 {
    SECTION DXE_DEPEX = instantnoodlep/ArmGicDxe/ArmGicDxe.depex
    SECTION PE32 = instantnoodlep/ArmGicDxe/ArmGicDxe.efi
    SECTION UI = "ArmGicDxe"
  }

FILE DRIVER = 49EA041E-6752-42CA-B0B1-7344FE2546B7 {
    SECTION DXE_DEPEX = instantnoodlep/ArmTimerDxe/ArmTimerDxe.depex
    SECTION PE32 = instantnoodlep/ArmTimerDxe/ArmTimerDxe.efi
    SECTION UI = "ArmTimerDxe"
  }    
  
FILE DRIVER = C2F9A4F5-F7B4-43E7-BA99-5EA804CC103A {
    SECTION PE32 = instantnoodlep/ASN1X509Dxe/ASN1X509Dxe.efi
    SECTION UI = "ASN1X509Dxe"
  }

FILE DRIVER = 5BD181DB-0487-4F1A-AE73-820E165611B3 {
    SECTION DXE_DEPEX = instantnoodlep/ButtonsDxe/ButtonsDxe.depex
    SECTION PE32 = instantnoodlep/ButtonsDxe/ButtonsDxe.efi
    SECTION UI = "ButtonsDxe"
  }  
  
FILE DRIVER = 42857F0A-13F2-4B21-8A23-53D3F714B840 {
    SECTION DXE_DEPEX = instantnoodlep/CapsuleRuntimeDxe/CapsuleRuntimeDxe.depex
    SECTION PE32 = instantnoodlep/CapsuleRuntimeDxe/CapsuleRuntimeDxe.efi
    SECTION UI = "CapsuleRuntimeDxe"
  }

FILE DRIVER = 2E3042F3-2BB9-463F-8866-56D75B7C4AB0 {
    SECTION DXE_DEPEX = instantnoodlep/ChargerExDxe/ChargerExDxe.depex
    SECTION PE32 = instantnoodlep/ChargerExDxe/ChargerExDxe.efi
    SECTION UI = "ChargerExDxe"
  }    
 
FILE DRIVER = 10E193DF-9966-44E7-B17C-59DD831E20FC {
    SECTION DXE_DEPEX = instantnoodlep/ChipInfo/ChipInfo.depex
    SECTION PE32 = instantnoodlep/ChipInfo/ChipInfo.efi
    SECTION UI = "ChipInfo"
  }

FILE DRIVER = 5F0937CD-73F9-445E-B320-BB6FD5D3CBDE {
    SECTION PE32 = instantnoodlep/CipherDxe/CipherDxe.efi
    SECTION UI = "CipherDxe"
  }  
  
FILE DRIVER = 4DB5DEA6-5302-4D1A-8A82-677A683B0D29 {
    SECTION DXE_DEPEX = instantnoodlep/ClockDxe/ClockDxe.depex
    SECTION PE32 = instantnoodlep/ClockDxe/ClockDxe.efi
    SECTION UI = "ClockDxe"
  }

FILE DRIVER = ABA01FF8-2CCB-4E12-8B2E-CD3F4A742993 {
    SECTION DXE_DEPEX = instantnoodlep/CmdDbDxe/CmdDbDxe.depex
    SECTION PE32 = instantnoodlep/CmdDbDxe/CmdDbDxe.efi
    SECTION UI = "CmdDbDxe"
  }    
  
FILE DRIVER = 51CCF399-4FDF-4E55-A45B-E123F84D456A {
    SECTION PE32 = instantnoodlep/ConPlatformDxe/ConPlatformDxe.efi
    SECTION UI = "ConPlatformDxe"
  }

FILE DRIVER = 408EDCEC-CF6D-477C-A5A8-B4844E3DE281 {
    SECTION PE32 = instantnoodlep/ConSplitterDxe/ConSplitterDxe.efi
    SECTION UI = "ConSplitterDxe"
  }  
  
FILE DRIVER = 1B52138D-3FA3-4E50-B958-20887353F809 {
    SECTION DXE_DEPEX = instantnoodlep/CPRDxe/CPRDxe.depex
    SECTION PE32 = instantnoodlep/CPRDxe/CPRDxe.efi
    SECTION UI = "CPRDxe"
  }

FILE DRIVER = 8E9BD160-B184-11DF-94E2-0800200C9A66 {
    SECTION DXE_DEPEX = instantnoodlep/DALSys/DALSys.depex
    SECTION PE32 = instantnoodlep/DALSys/DALSys.efi
    SECTION UI = "DALSys"
  }    
    
FILE DRIVER = 8681CC5A-0DF6-441E-B4B8-E915C538F067 {
    SECTION DXE_DEPEX = instantnoodlep/DALTLMM/DALTLMM.depex
    SECTION PE32 = instantnoodlep/DALTLMM/DALTLMM.efi
    SECTION UI = "DALTLMM"
  }

FILE DRIVER = 7DB0793A-4402-4BE1-906E-D0FABAD2707E {
    SECTION DXE_DEPEX = instantnoodlep/DDRInfoDxe/DDRInfoDxe.depex
    SECTION PE32 = instantnoodlep/DDRInfoDxe/DDRInfoDxe.efi
    SECTION UI = "DDRInfoDxe"
  }  
  
FILE DRIVER = 9B680FCE-AD6B-4F3A-B60B-F59899003443 {
    SECTION DXE_DEPEX = instantnoodlep/DevicePathDxe/DevicePathDxe.depex
    SECTION PE32 = instantnoodlep/DevicePathDxe/DevicePathDxe.efi
    SECTION UI = "DevicePathDxe"
  }

FILE DRIVER = 6B38F7B4-AD98-40E9-9093-ACA2B5A253C4 {
    SECTION PE32 = instantnoodlep/DiskIoDxe/DiskIoDxe.efi
    SECTION UI = "DiskIoDxe"
  }    
  
FILE DRIVER = 4138022F-06C7-4F79-9C94-7E33B511A4E7 {
    SECTION DXE_DEPEX = instantnoodlep/DisplayDxe/DisplayDxe.depex
    SECTION PE32 = instantnoodlep/DisplayDxe/DisplayDxe.efi
    SECTION UI = "DisplayDxe"
  }

FILE DRIVER = D6A2CB7F-6A18-4E2F-B43B-9920A733700A {
    SECTION PE32 = instantnoodlep/DxeCore/DxeCore.efi
    SECTION UI = "DxeCore"
  }  
  
FILE DRIVER = 37795BA0-E1CF-4ED5-BD8B-16DF6BCB1E1A {
    SECTION DXE_DEPEX = instantnoodlep/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.depex
    SECTION PE32 = instantnoodlep/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.efi
    SECTION UI = "EmbeddedMonotonicCounter"
  }

FILE DRIVER = CD3BAFB6-50FB-4FE8-8E4E-AB74D2C1A600 {
    SECTION PE32 = instantnoodlep/EnglishDxe/EnglishDxe.efi
    SECTION UI = "EnglishDxe"
  }    
  
FILE DRIVER = 90A49AFD-422F-08AE-9611-E788D3804845 {
    SECTION DXE_DEPEX = instantnoodlep/EnvDxe/EnvDxe.depex
    SECTION PE32 = instantnoodlep/EnvDxe/EnvDxe.efi
    SECTION UI = "EnvDxe"
  }

FILE DRIVER = 961578FE-B6B7-44C3-AF35-6BC705CD2B1F {
    SECTION PE32 = instantnoodlep/Fat/Fat.efi
    SECTION UI = "Fat"
  }  
  
FILE DRIVER = 1C04F529-0612-4319-9315-B2E75C16810A {
    SECTION PE32 = instantnoodlep/FeatureEnablerDxe/FeatureEnablerDxe.efi
    SECTION UI = "FeatureEnablerDxe"
  }

FILE DRIVER = ED15FFD5-BC96-4107-9118-95366600188E {
    SECTION DXE_DEPEX = instantnoodlep/FontDxe/FontDxe.depex
    SECTION PE32 = instantnoodlep/FontDxe/FontDxe.efi
    SECTION UI = "FontDxe"
  }    
  
FILE DRIVER = 907125C0-A5F1-11E3-A3FE-A3198B49350C {
    SECTION PE32 = instantnoodlep/FvSimpleFileSystem/FvSimpleFileSystem.efi
    SECTION UI = "FvSimpleFileSystem"
  }

FILE DRIVER = 569EA0DE-B557-4043-84CF-01103FE516E5 {
    SECTION DXE_DEPEX = instantnoodlep/GpiDxe/GpiDxe.depex
    SECTION PE32 = instantnoodlep/GpiDxe/GpiDxe.efi
    SECTION UI = "GpiDxe"
  }  
  
FILE DRIVER = CCCB0C28-4B24-11D5-9A5A-0090273FC14D {
    SECTION PE32 = instantnoodlep/GraphicsConsoleDxe/GraphicsConsoleDxe.efi
    SECTION UI = "GraphicsConsoleDxe"
  }

FILE DRIVER = 9A00771F-36D4-4DD5-8916-C48ED9B16B86 {
    SECTION DXE_DEPEX = instantnoodlep/HALIOMMU/HALIOMMU.depex
    SECTION PE32 = instantnoodlep/HALIOMMU/HALIOMMU.efi
    SECTION UI = "HALIOMMU"
  }    
  
FILE DRIVER = 3ADF8DDA-1850-44C5-8C63-BB991849BC6F {
    SECTION PE32 = instantnoodlep/HashDxe/HashDxe.efi
    SECTION UI = "HashDxe"
  }

FILE DRIVER = 348C4D62-BFBD-4882-9ECE-C80BB1C4783B {
    SECTION DXE_DEPEX = instantnoodlep/HiiDatabase/HiiDatabase.depex
    SECTION PE32 = instantnoodlep/HiiDatabase/HiiDatabase.efi
    SECTION UI = "HiiDatabase"
  }  
  
FILE DRIVER = AF9763A2-033B-4109-8E17-56A98D380C92 {
    SECTION DXE_DEPEX = instantnoodlep/HWIODxeDriver/HWIODxeDriver.depex
    SECTION PE32 = instantnoodlep/HWIODxeDriver/HWIODxeDriver.efi
    SECTION UI = "HWIODxeDriver"
  }

FILE DRIVER = 04DE8591-D2B3-4077-BBBE-B12070094EB6 {
    SECTION DXE_DEPEX = instantnoodlep/I2C/I2C.depex
    SECTION PE32 = instantnoodlep/I2C/I2C.efi
    SECTION UI = "I2C"
  }    
  
FILE DRIVER = F09AD92E-4E91-490F-AB99-E69939B840B2 {
    SECTION PE32 = instantnoodlep/LimitsDxe/LimitsDxe.efi
    SECTION UI = "LimitsDxe"
  }

FILE DRIVER = 20583A66-3C26-4D9E-9A8C-E2DFA2914015 {
    SECTION PE32 = instantnoodlep/MacDxe/MacDxe.efi
    SECTION UI = "MacDxe"
  }  
  
FILE DRIVER = 4C6E0267-C77D-410D-8100-1495911A989D {
    SECTION DXE_DEPEX = instantnoodlep/MetronomeDxe/MetronomeDxe.depex
    SECTION PE32 = instantnoodlep/MetronomeDxe/MetronomeDxe.efi
    SECTION UI = "MetronomeDxe"
  }

FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219711 {
    SECTION DXE_DEPEX = instantnoodlep/NpaDxe/NpaDxe.depex
    SECTION PE32 = instantnoodlep/NpaDxe/NpaDxe.efi
    SECTION UI = "NpaDxe"
  }    
  
FILE DRIVER = 3AEC2036-C55A-569F-9BD6-B144A55DF39F {
    SECTION PE32 = instantnoodlep/OGaugeAuthDxe/OGaugeAuthDxe.efi
    SECTION UI = "OGaugeAuthDxe"
  }

FILE DRIVER = 9589512A-5370-11E3-8631-D7C5958374C8 {
    SECTION PE32 = instantnoodlep/OplusDlAPP/OplusDlAPP.efi
    SECTION UI = "OplusDlAPP"
  }  
  
FILE DRIVER = 68A710AB-A58D-4C0B-BE1E-5F6EE2C36AD8 {
    SECTION DXE_DEPEX = instantnoodlep/OplusProject/OplusProject.depex
    SECTION PE32 = instantnoodlep/OplusProject/OplusProject.efi
    SECTION UI = "OplusProject"
  }

FILE DRIVER = 1FA1F39E-FEFF-4AAE-BD7B-38A070A3B609 {
    SECTION PE32 = instantnoodlep/PartitionDxe/PartitionDxe.efi
    SECTION UI = "PartitionDxe"
  }    
  
FILE DRIVER = B43C22DB-6333-490C-872D-0A73439059FD {
    SECTION DXE_DEPEX = instantnoodlep/PdcDxe/PdcDxe.depex
    SECTION PE32 = instantnoodlep/PdcDxe/PdcDxe.efi
    SECTION UI = "PdcDxe"
  }

FILE DRIVER = 82ACEBF1-DA4C-41DD-BE84-68EC2AA32DB9 {
    SECTION DXE_DEPEX = instantnoodlep/PhoenixDxe/PhoenixDxe.depex
    SECTION PE32 = instantnoodlep/PhoenixDxe/PhoenixDxe.efi
    SECTION UI = "PhoenixDxe"
  }  
  
FILE DRIVER = 1D317734-4083-47C6-83EA-E3A42F2A6BFF {
    SECTION DXE_DEPEX = instantnoodlep/PILDxe/PILDxe.depex
    SECTION PE32 = instantnoodlep/PILDxe/PILDxe.efi
    SECTION UI = "PILDxe"
  }

FILE DRIVER = 8CF9C920-D5E6-4DAC-BEF9-6E6A4EEC7ADD {
    SECTION DXE_DEPEX = instantnoodlep/PILProxyDxe/PILProxyDxe.depex
    SECTION PE32 = instantnoodlep/PILProxyDxe/PILProxyDxe.efi
    SECTION UI = "PILProxyDxe"
  }    
  
FILE DRIVER = B105211B-BBBD-4ADD-A3B0-D1CF4A52154C {
    SECTION DXE_DEPEX = instantnoodlep/PlatformInfoDxeDriver/PlatformInfoDxeDriver.depex
    SECTION PE32 = instantnoodlep/PlatformInfoDxeDriver/PlatformInfoDxeDriver.efi
    SECTION UI = "PlatformInfoDxeDriver"
  }

FILE DRIVER = 5776232E-082D-4B75-9A0E-FE1D13F7A5D9 {
    SECTION DXE_DEPEX = instantnoodlep/PmicDxe/PmicDxe.depex
    SECTION PE32 = instantnoodlep/PmicDxe/PmicDxe.efi
    SECTION UI = "PmicDxe"
  }  
  
FILE DRIVER = 79E4A61C-ED73-4312-94FE-E3E7563362A9 {
    SECTION DXE_DEPEX = instantnoodlep/PrintDxe/PrintDxe.depex
    SECTION PE32 = instantnoodlep/PrintDxe/PrintDxe.efi
    SECTION UI = "PrintDxe"
  }

FILE DRIVER = 0401B830-BFF9-44A2-A5F6-95734A33C017 {
    SECTION DXE_DEPEX = instantnoodlep/PwrUtilsDxe/PwrUtilsDxe.depex
    SECTION PE32 = instantnoodlep/PwrUtilsDxe/PwrUtilsDxe.efi
    SECTION UI = "PwrUtilsDxe"
  }    
  
FILE DRIVER = 5A50AA81-C3AE-4608-A0E3-41A2E69BAF94 {
    SECTION DXE_DEPEX = instantnoodlep/QcomBds/QcomBds.depex
    SECTION PE32 = instantnoodlep/QcomBds/QcomBds.efi
    SECTION UI = "QcomBds"
  }

FILE DRIVER = EEE9C2B1-16CA-4F34-87EA-2E6D1E160CC4 {
    SECTION PE32 = instantnoodlep/QcomChargerApp/QcomChargerApp.efi
    SECTION UI = "QcomChargerApp"
  }  
  
FILE DRIVER = 4BCE7F36-428E-4393-99E3-7E0844404DBA {
    SECTION DXE_DEPEX = instantnoodlep/QcomChargerDxeLA/QcomChargerDxeLA.depex
    SECTION PE32 = instantnoodlep/QcomChargerDxeLA/QcomChargerDxeLA.efi
    SECTION UI = "QcomChargerDxeLA"
  }

FILE DRIVER = 040E1E61-0AFB-411B-9EC9-00F3FC59CC13 {
    SECTION DXE_DEPEX = instantnoodlep/QcomWDogDxe/QcomWDogDxe.depex
    SECTION PE32 = instantnoodlep/QcomWDogDxe/QcomWDogDxe.efi
    SECTION UI = "QcomWDogDxe"
  }    
  
FILE DRIVER = B336F62D-4135-4A55-AE4E-4971BBF0885D {
    SECTION DXE_DEPEX = instantnoodlep/RealTimeClock/RealTimeClock.depex
    SECTION PE32 = instantnoodlep/RealTimeClock/RealTimeClock.efi
    SECTION UI = "RealTimeClock"
  }

FILE DRIVER = 3AE17DB7-3CC5-4B89-9304-9549211057EF {
    SECTION DXE_DEPEX = instantnoodlep/ResetRuntimeDxe/ResetRuntimeDxe.depex
    SECTION PE32 = instantnoodlep/ResetRuntimeDxe/ResetRuntimeDxe.efi
    SECTION UI = "ResetRuntimeDxe"
  }  
  
FILE DRIVER = B0D3689E-11F8-43C6-8ECE-023A29CEC35B {
    SECTION PE32 = instantnoodlep/RngDxe/RngDxe.efi
    SECTION UI = "RngDxe"
  }

FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219766 {
    SECTION DXE_DEPEX = instantnoodlep/RpmhDxe/RpmhDxe.depex
    SECTION PE32 = instantnoodlep/RpmhDxe/RpmhDxe.efi
    SECTION UI = "RpmhDxe"
  }    
  
FILE DRIVER = D93CE3D8-A7EB-4730-8C8E-CC466A9ECC3C {
    SECTION DXE_DEPEX = instantnoodlep/RscRtDxe/RscRtDxe.depex
    SECTION PE32 = instantnoodlep/RscRtDxe/RscRtDxe.efi
    SECTION UI = "RscRtDxe"
  }

FILE DRIVER = B601F8C4-43B7-4784-95B1-F4226CB40CEE {
    SECTION DXE_DEPEX = instantnoodlep/RuntimeDxe/RuntimeDxe.depex
    SECTION PE32 = instantnoodlep/RuntimeDxe/RuntimeDxe.efi
    SECTION UI = "RuntimeDxe"
  }  
  
FILE DRIVER = 6C2004EF-4E0E-4BE4-B14C-340EB4AA5891 {
    SECTION DXE_DEPEX = instantnoodlep/SCHandlerRtDxe/SCHandlerRtDxe.depex
    SECTION PE32 = instantnoodlep/SCHandlerRtDxe/SCHandlerRtDxe.efi
    SECTION UI = "SCHandlerRtDxe"
  }

FILE DRIVER = 2D7A83E3-E343-4FFB-9109-631F2EE11694 {
    SECTION DXE_DEPEX = instantnoodlep/ScmDxe/ScmDxe.depex
    SECTION PE32 = instantnoodlep/ScmDxe/ScmDxe.efi
    SECTION UI = "ScmDxe"
  }    

FILE DRIVER = F10F76DB-42C1-533F-34A8-69BE24653110 {
    SECTION DXE_DEPEX = instantnoodlep/SdccDxe/SdccDxe.depex
    SECTION PE32 = instantnoodlep/SdccDxe/SdccDxe.efi
    SECTION UI = "SdccDxe"
  }    

FILE DRIVER = 32C71E68-83A8-46ED-AED1-094E71B12057 {
    SECTION PE32 = instantnoodlep/SecRSADxe/SecRSADxe.efi
    SECTION UI = "SecRSADxe"
  }    

FILE DRIVER = F80697E9-7FD6-4665-8646-88E33EF71DFC {
    SECTION DXE_DEPEX = instantnoodlep/SecurityStubDxe/SecurityStubDxe.depex
    SECTION PE32 = instantnoodlep/SecurityStubDxe/SecurityStubDxe.efi
    SECTION UI = "SecurityStubDxe"
  }    

FILE DRIVER = 9C1EB71F-DD6C-4ED5-9F6A-5CC0CA789F16 {
    SECTION DXE_DEPEX = instantnoodlep/ShmBridgeDxe/ShmBridgeDxe.depex
    SECTION PE32 = instantnoodlep/ShmBridgeDxe/ShmBridgeDxe.efi
    SECTION UI = "ShmBridgeDxe"
  }    

FILE DRIVER = 857A8741-0EEC-43BD-9482-27D14ED47D72 {
    SECTION DXE_DEPEX = instantnoodlep/SimpleTextInOutSerial/SimpleTextInOutSerial.depex
    SECTION PE32 = instantnoodlep/SimpleTextInOutSerial/SimpleTextInOutSerial.efi
    SECTION UI = "SimpleTextInOutSerial"
  }    

FILE DRIVER = F541D663-4A48-40AA-AABF-FF158CCAE34C {
    SECTION DXE_DEPEX = instantnoodlep/SmemDxe/SmemDxe.depex
    SECTION PE32 = instantnoodlep/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
  }    

FILE DRIVER = 7A32BD23-F735-4F57-AA1A-447D2FE3BE0D {
    SECTION DXE_DEPEX = instantnoodlep/SPI/SPI.depex
    SECTION PE32 = instantnoodlep/SPI/SPI.efi
    SECTION UI = "SPI"
  }    

FILE DRIVER = 2A7B4BEF-80CD-49E1-B473-374BA4D673FC {
    SECTION DXE_DEPEX = instantnoodlep/SPMI/SPMI.depex
    SECTION PE32 = instantnoodlep/SPMI/SPMI.efi
    SECTION UI = "SPMI"
  }    

FILE DRIVER = 5D787B6C-6254-43F5-A7A8-CB25329CF97E {
    SECTION DXE_DEPEX = instantnoodlep/SPSSDxe/SPSSDxe.depex
    SECTION PE32 = instantnoodlep/SPSSDxe/SPSSDxe.efi
    SECTION UI = "SPSSDxe"
  }    

FILE DRIVER = F09AD92E-485C-9CDB-3E05-3385C38F94CC {
    SECTION DXE_DEPEX = instantnoodlep/TsensDxe/TsensDxe.depex
    SECTION PE32 = instantnoodlep/TsensDxe/TsensDxe.efi
    SECTION UI = "TsensDxe"
  }    

FILE DRIVER = 6925FAD3-E243-4B69-AD61-3F978C8ABC60 {
    SECTION DXE_DEPEX = instantnoodlep/TzDxe/TzDxe.depex
    SECTION PE32 = instantnoodlep/TzDxe/TzDxe.efi
    SECTION UI = "TzDxe"
  }    

FILE DRIVER = 0D35CD8E-97EA-4F9A-96AF-0F0D89F76567 {
    SECTION DXE_DEPEX = instantnoodlep/UFSDxe/UFSDxe.depex
    SECTION PE32 = instantnoodlep/UFSDxe/UFSDxe.efi
    SECTION UI = "UFSDxe"
  }    

FILE DRIVER = E43128A8-8692-42B6-8AFA-676158578D18 {
    SECTION DXE_DEPEX = instantnoodlep/ULogDxe/ULogDxe.depex
    SECTION PE32 = instantnoodlep/ULogDxe/ULogDxe.efi
    SECTION UI = "ULogDxe"
  }    

FILE DRIVER = 240612B7-A063-11D4-9A3A-0090273FC14D {
    SECTION PE32 = instantnoodlep/UsbBusDxe/UsbBusDxe.efi
    SECTION UI = "UsbBusDxe"
  }    

FILE DRIVER = CD823A4D-7DEC-4531-AE5D-4134FA4127B8 {
    SECTION DXE_DEPEX = instantnoodlep/UsbConfigDxe/UsbConfigDxe.depex
    SECTION PE32 = instantnoodlep/UsbConfigDxe/UsbConfigDxe.efi
    SECTION UI = "UsbConfigDxe"
  }    

FILE DRIVER = 3299A266-15F0-4346-8318-716336736D3E {
    SECTION DXE_DEPEX = instantnoodlep/UsbDeviceDxe/UsbDeviceDxe.depex
    SECTION PE32 = instantnoodlep/UsbDeviceDxe/UsbDeviceDxe.efi
    SECTION UI = "UsbDeviceDxe"
  }    

FILE DRIVER = 94F8A6A7-DC34-4101-88C1-99179CCEAE83 {
    SECTION DXE_DEPEX = instantnoodlep/UsbfnDwc3Dxe/UsbfnDwc3Dxe.depex
    SECTION PE32 = instantnoodlep/UsbfnDwc3Dxe/UsbfnDwc3Dxe.efi
    SECTION UI = "UsbfnDwc3Dxe"
  }    

FILE DRIVER = 0A134F0E-075E-40B3-9C63-3B3906804663 {
    SECTION DXE_DEPEX = instantnoodlep/UsbInitDxe/UsbInitDxe.depex
    SECTION PE32 = instantnoodlep/UsbInitDxe/UsbInitDxe.efi
    SECTION UI = "UsbInitDxe"
  } 

FILE DRIVER = 2D2E62CF-9ECF-43B7-8219-94E7FC713DFE {
    SECTION PE32 = instantnoodlep/UsbKbDxe/UsbKbDxe.efi
    SECTION UI = "UsbKbDxe"
  }

FILE DRIVER = 9FB4B4A7-42C0-4BCD-8540-9BCC6711F83E {
    SECTION PE32 = instantnoodlep/UsbMassStorageDxe/UsbMassStorageDxe.efi
    SECTION UI = "UsbMassStorageDxe"
  }

FILE DRIVER = 5AF77F10-90DF-4E7E-8325-A17EC09D5443 {
    SECTION DXE_DEPEX = instantnoodlep/UsbMsdDxe/UsbMsdDxe.depex
    SECTION PE32 = instantnoodlep/UsbMsdDxe/UsbMsdDxe.efi
    SECTION UI = "UsbMsdDxe"
  }

FILE DRIVER = 11FAED4C-B21F-4D88-8E48-C4C28A1E50DF {
    SECTION DXE_DEPEX = instantnoodlep/UsbPwrCtrlDxe/UsbPwrCtrlDxe.depex
    SECTION PE32 = instantnoodlep/UsbPwrCtrlDxe/UsbPwrCtrlDxe.efi
    SECTION UI = "UsbPwrCtrlDxe"
  }

FILE DRIVER = 2B0ECDCE-01AE-446E-9FFD-C4217DE0340F {
    SECTION DXE_DEPEX = instantnoodlep/VariableDxe/VariableDxe.depex
    SECTION PE32 = instantnoodlep/VariableDxe/VariableDxe.efi
    SECTION UI = "VariableDxe"
  }

FILE DRIVER = 8BD3B475-401A-4B0B-9315-EDEE61A1EAE5 {
    SECTION DXE_DEPEX = instantnoodlep/VcsDxe/VcsDxe.depex
    SECTION PE32 = instantnoodlep/VcsDxe/VcsDxe.efi
    SECTION UI = "VcsDxe"
  }

FILE DRIVER = A25F5839-4D55-428F-8F0B-5CE1D565F53E {
    SECTION DXE_DEPEX = instantnoodlep/VerifiedBootDxe/VerifiedBootDxe.depex
    SECTION PE32 = instantnoodlep/VerifiedBootDxe/VerifiedBootDxe.efi
    SECTION UI = "VerifiedBootDxe"
  }

FILE DRIVER = F099D67F-71AE-4C36-B2A3-DCEB0EB2B7D8 {
    SECTION DXE_DEPEX = instantnoodlep/WatchdogTimer/WatchdogTimer.depex
    SECTION PE32 = instantnoodlep/WatchdogTimer/WatchdogTimer.efi
    SECTION UI = "WatchdogTimer"
  }

FILE DRIVER = B7F50E91-A759-412C-ADE4-DCD03E7F7C28 {
    SECTION PE32 = instantnoodlep/XhciDxe/XhciDxe.efi
    SECTION UI = "XhciDxe"
  }

FILE DRIVER = BEB12BEE-F6E1-11E1-9FB8-6C626DE4AEB1 {
    SECTION DXE_DEPEX = instantnoodlep/XhciPciEmulation/XhciPciEmulation.depex
    SECTION PE32 = instantnoodlep/XhciPciEmulation/XhciPciEmulation.efi
    SECTION UI = "XhciPciEmulation"
  }
